apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
{{- if .Values.service.externalIPs }}
  externalIPs:
{{ toYaml .Values.service.externalIPs | indent 4 }}
{{- end }}
{{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: "{{ .Values.service.loadBalancerIP }}"
{{- end }}

{{- if .Values.service.ports }}
  ports:
  {{- range .Values.service.ports }}
    - port: {{ .port }}
      targetPort: {{ .targetPort | default .port }}
      protocol: {{ .protocol | default "TCP" }}
      {{- $protocol := .protocol | default "tcp" }}
      {{- $defaultPortName := printf "%s-%v" $protocol .port }}
      name: {{ lower (.name | default $defaultPortName) }}
  {{- end }}
{{- else }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort | default .Values.service.port }}
      protocol: {{ .Values.service.protocol | default "TCP" }}
      {{- if .Values.service.protocol }}
      name: {{ lower .Values.service.protocol }}-{{ .Values.service.port }}
      {{- else }}
      name: tcp-{{ .Values.service.port }}
      {{- end }}
{{- end }}

  selector:
    {{- include "chart.selectorLabels" . | nindent 4 }}
