{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  labels:
{{ include "ioops-template.labels" . | nindent 4 }}
{{- end -}}