{{- if .Values.vpa.enabled -}}
{{- $fullName := include "chart.fullname" . -}}
apiVersion: "autoscaling.k8s.io/v1"
kind: VerticalPodAutoscaler
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "chart.fullname" . }}
  updatePolicy:
    updateMode: {{ .Values.vpa.updateMode | default "Off" | quote }}
{{- end }}